### ISSUE TITLE
Current To-Do List

### ISSUE THREAD

**Issue by vincentlaucsb** [dcamposliz/int7x#1]
- [ ] CSS needs to be refactored
- [ ] Progress bar for projects was broken
- [ ] Add syntax highlighting
- [ ] Write a test suite
